#!/bin/sh

# A Fork of <https://wiki.gentoo.org/wiki/Simple_sandbox>

# Author:       Ahmed Elhori <dev@elhori.com>
# License:      GNU GPLv3
# Description:  A simple sandbox for every application

# ENV
set -e
NAME="$(basename "$0")"
pkg_name="$1"
sandbox_pkg_name="$2"
sandbox_user="$3"
main_user="$4"

print_error(){
	message="$1"
	echo "${NAME} - Error: ${message}" >&2
}

check_input(){
	if [ "$#" -ne '4' ]; then
		print_error "Usage: '# simple-sandbox <package_name> <sandbox_package_name> <sandbox_user> <main_user>'."
		return 1
	fi
}

check_root(){
	if [ "$(id -u)" -ne '0' ]; then
		print_error 'Please run as root.'
		return 1
	fi
}

check_package_available(){
	if ! command -v "$pkg_name" >/dev/null 2>&1; then
		print_error "$pkg_name not found."
		return 1
	fi
}

create_sandbox_user(){
	useradd --create-home --shell '/bin/false' "$sandbox_user"
}

add_main_user_to_sandbox_group(){
	usermod -aG "$sandbox_user" "$main_user"
}

generate_sudoers(){
	echo "${main_user} ALL=(${sandbox_user}) NOPASSWD: ALL" > /etc/sudoers.d/"$sandbox_user"
}

create_executable(){
	cat <<- EOF > /usr/local/bin/"$sandbox_pkg_name"
		#!/bin/sh

		xhost si:localuser:${sandbox_user} && sudo -u ${sandbox_user} ${pkg_name} "\$@"
	EOF

	chown "$main_user":"$main_user" /usr/local/bin/"$sandbox_pkg_name"
	chmod 700 /usr/local/bin/"$sandbox_pkg_name"
}

config_audio(){
	mkdir -p /home/"$main_user"/.config/pulse
	mkdir -p /home/"$sandbox_user"/.config/pulse
	printf '.include /etc/pulse/default.pa\nload-module module-native-protocol-unix auth-anonymous=1 socket=/tmp/pulse-socket' > /home/"$main_user"/.config/pulse/default.pa
	printf 'default-server = unix:/tmp/pulse-socket' > /home/"$sandbox_user"/.config/pulse/client.conf
	chown "$main_user":"$main_user" /home/"$main_user"/.config/pulse/default.pa
	chmod 700 /home/"$main_user"/.config/pulse/default.pa
}

change_permissions(){
	chown -R "$sandbox_user":"$main_user" /home/"$sandbox_user"
	find /home/"$sandbox_user" -type d -exec chmod -R g+rx {} \;
	find /home/"$sandbox_user" -type f -exec chmod -R g+r {} \;
}

print_finish(){
	echo "Run using: ${sandbox_pkg_name}"
}

main(){
	check_input "$@"
	check_root
	check_package_available
	create_sandbox_user
	add_main_user_to_sandbox_group
	generate_sudoers
	create_executable
	config_audio
	change_permissions
	print_finish
}

main "$@"
